// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table Weather (StartTime:datetime, EndTime:datetime, EpisodeId:long, EventId:long, State:string, EventType:string, InjuriesDirect:long, InjuriesIndirect:long, DeathsDirect:long, DeathsIndirect:long, DamageProperty:long, DamageCrops:long, Source:string, BeginLocation:string, EndLocation:string, BeginLat:real, BeginLon:real, EndLat:real, EndLon:real, EpisodeNarrative:string, EventNarrative:string, StormSummary:dynamic) 
